### ISSUE TITLE
the overall app feels very laggy since the addition of the new layout

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#101]

**Comment by JoeGruffins** [comment]
Is there a link to the changes specifically that led from not laggy -> laggy? What commits?

**Comment by dreacot** [comment]
I think it's started from when we added the carousel/silder for the asset balance

https://github.com/crypto-power/cryptopower/commit/7024efb21075b39ed0fc46f4f6a21ee93a196f99

**Comment by JoeGruffins** [comment]
I'll take a whack at this.

**Comment by JoeGruffins** [comment]
![profile001](https://github.com/crypto-power/cryptopower/assets/34998433/c1b7c901-4788-4312-946c-2665c8615ca8)

**Comment by JoeGruffins** [comment]
That one was too close to startup, this one shows the problem better I think
![profile001](https://github.com/crypto-power/cryptopower/assets/34998433/60fe08c9-43ca-4350-98d1-3438b69b5a70)
