### ISSUE TITLE
When the app is launched syncing doesn't start for wallets until you navigate to the wallets tab

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#107]
![Image](https://github.com/crypto-power/cryptopower/assets/25265396/4310ad2c-414b-4e78-bac8-330ae501f5ee)

**Comment by JoeGruffins** [comment]
I rather thought this was a feature. Probably most users do want sync to start immediately though.

**Comment by dreacot** [comment]
Currently it's a bug, because sync is already enabled previously for those wallets, but it doesn't register until the wallets tab is clicked. They aren't fresh wallets, for fresh wallets sync is disabled by default and have to manually be enabled, which turns on auto sync, and remains enabled until the user turns it off

**Comment by JoeGruffins** [comment]
Oh I see. Ok that looks like a bug then.
