### ISSUE TITLE
[Governance]: create a governance tab entry after the trade tab

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#130]
create a governance tab entry after the trade tab, and move the contents of the Voting Page as seen below into the Governance tab.

Voting Menu entry can be removed from Decred wallet menu entry, since you don't need a DCR wallet to view proposals, you only need a DCR wallet to cast votes.

Casting votes would be done via a modal that allows you to pick the DCR wallet/account you wish to use in voting

Note this issue mainly has to do with moving the page to a different location, the proposal cards should not be redesigned as part of this issue.

The segmented control can replace the governance sub menu as seen in the screenshot

![Governance - proposal](https://github.com/crypto-power/cryptopower/assets/25265396/3d307f49-d8d1-4188-9e88-0e1e5636db54)

![Image](https://github.com/crypto-power/cryptopower/assets/25265396/c23f7d1f-d24c-495b-8fbb-ad1960fdfae8)

**Comment by xaur** [comment]
On the [screenshot](https://user-images.githubusercontent.com/25265396/274982883-3d307f49-d8d1-4188-9e88-0e1e5636db54.png) above the top level tabs before this change were all multi-asset:

- Overview shows various data for all owned assets
- Wallets or Assets is not shown above but I assume it shows different views depending on what wallet is selected
- Trade allows to trade between different assets
- ... but Governance is all specific to Decred?

Decred Governance made sense as one of Decred Wallet tabs as seen on the [second screenshot](https://user-images.githubusercontent.com/25265396/271443969-c23f7d1f-d24c-495b-8fbb-ad1960fdfae8.png) but making it a top-level tab feels odd. As a thought experiment imagine making Staking or StakeShuffle a top-level tab.

I'm not aware of design plans though, perhaps the Governance tab will get an asset/network switch to become multi-asset like the other top level tabs?

**Comment by dreacot** [comment]
The idea behind that was that you did not need a decred wallet to view proposals/consensus changes, you only needed a decred wallet to vote. We believed having governance as a top level menu was another way to promote Decred trough the wallet.

People are able to view proposals without having to create a Decred wallet, and would only need to create one if they vote.

Plus the Governance tab in every Decred wallet contained redundant data across all Decred wallets

**Comment by xaur** [comment]
> People are able to view proposals without having to create a Decred wallet, and would only need to create one if they vote.

I see. My comparison with Staking and StakeShuffle is incorrect then, those require a DCR wallet.

The logical presentation can still be improved I think, Governance needs to make it clear it is Decred Governance. Imagine adding another coin with governance features, its proposals would need to go in Governance as well, with some asset/network selector.

Another aspect is that Decred's governance views may have two modes. First is "public data only" mode not customized with any wallet data (as on the screenshots). Second is same as first but enhanced with extra information if viewed through the lens of a specific Decred wallet:

- Proposals may show wallet's cast votes/choices and remaining eligible votes
- Consensus votes may show wallet's voting preferences + some VSP info if VSP is involved in voting
- TSpend votes may show wallet's voting preferences for Pi keys and TSpends

To show these there must be a wallet selector somewhere I guess. It's a good design challenge.

**Comment by dreacot** [comment]
when dcr wallets are present the user sees a dropdown, that is correct

![Governance - proposal (1)](https://github.com/crypto-power/cryptopower/assets/25265396/4759b70a-2202-4672-8a19-0fb8a113b331)
