### ISSUE TITLE
Overview Slider image Size Bug

### ISSUE THREAD

**Issue by Sirmorrison** [crypto-power/cryptopower#140]
Currently, on the overview coin slider image layout looks like this.
![image](https://github.com/crypto-power/cryptopower/assets/27733432/70ba5037-8164-4f89-a599-2a82aac5289d)

A fix I will like to recommend will be for the coin image to be wrapped by a card or linearLayout that way, regardless of the image size, the image adoptes the size of what ever layout it is in. 

Right now, the image is extending beyond the layout it is in.

**Comment by JoeGruffins** [comment]
What should it look like? A rectangle? Or should the edges be round like on the left? Rounder?

**Comment by dreacot** [comment]
this is what it should look like

![Image](https://github.com/crypto-power/cryptopower/assets/25265396/a1e3e84a-908e-44e0-a196-ba4eb7cc9ea0)
