### ISSUE TITLE
[proposals]: trying to open the vote modal crashes the app

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#165]
i had previously voted for the proposal in the screenshot below

![Screenshot from 2023-10-09 15-32-05](https://github.com/crypto-power/cryptopower/assets/25265396/aa7740f2-2a1a-4a68-8505-0fa50b92ceb4)

i wanted to add more votes so i clicked on the vote modal

![Screenshot from 2023-10-09 15-32-29](https://github.com/crypto-power/cryptopower/assets/25265396/69ebe951-9241-485b-b4ac-2cf2dc7f3661)

the modal kept loading till the app crashed

see crash log below

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12a366b]

goroutine 1621 [running]:
github.com/crypto-power/cryptopower/ui/page/governance.newVoteModal.func1.1()
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/governance/proposal_vote_modal.go:81 +0xeb
created by github.com/crypto-power/cryptopower/ui/page/governance.newVoteModal.func1
        /home/kennedy/Projects/src/github.com/cryptopower/cryptopower/ui/page/governance/proposal_vote_modal.go:77 +0x205
exit status 2
```

**Comment by JoeGruffins** [comment]
Will try to reproduce.
