### ISSUE TITLE
UI: Top navigation gone after wallet backup.

### ISSUE THREAD

**Issue by JoeGruffins** [crypto-power/cryptopower#168]
https://github.com/crypto-power/cryptopower/assets/34998433/bb480b06-303a-4d3c-be44-ed51fb42fdab

**Comment by JustinBeBoy** [comment]
I can't reproduce, despite trying many ways

**Comment by dreacot** [comment]
might have been resolved in https://github.com/crypto-power/cryptopower/pull/185

**Comment by JoeGruffins** [comment]
Oh yeah looks fixed on master, closing.
