### ISSUE TITLE
"Back to wallets" button not responsive on backup verification screen

### ISSUE THREAD

**Issue by peterzen** [crypto-power/cryptopower#242]
On the back finalization screen the "Back to Wallets" button doesn't respond to click, doesn't take back to the Wallets.  When it's clicked, the below messages are logged:

```
2023-11-06 16:52:58.811 [DBG] UI: Error starting sync: sync_already_in_progress
2023-11-06 16:52:58.811 [DBG] UI: Error starting sync: sync_already_in_progress
```

![image](https://github.com/crypto-power/cryptopower/assets/5878500/f646f72c-d9cd-4c40-94b4-0a10753ebbe6)

To reproduce:

- Select DCR wallet (simnet)
- Backup wallet
- Copy seed words
- Paste them in

**Comment by dreacot** [comment]
resolved
