### ISSUE TITLE
Refactor app.PageStack.Push(...)

### ISSUE THREAD

**Issue by ukane-philemon** [crypto-power/cryptopower#252]
Currently, `app.PageStack.Push(...)` does more than push a new page to the page stack, it also binds the page to a navigator and executes the `OnNavigateTo` method on the page. IMO, `Push` should do nothing more than its name suggests. Removing duplicates before adding a new page in pageStack.Push is acceptable but I think it's better and more intuitive for its caller to bind the page as required and execute the `OnNavigateTo` method.

Any thoughts @dreacot? I have some code suggestions we can discuss if we're okay with this refactor.

**Comment by dreacot** [comment]
if we are to push a new page, one of the first callbacks to be executed is the `onNavigatedTo` method, i don't think the caller should be the one triggering that. i see no reason we would want the caller to do that, it doesn't seem natural. the caller shouldn't have to bother about what happens under the hood when moving to a new page

**Comment by itswisdomagain** [comment]
> `Push` should do nothing more than its name suggests

Remember `Push` is a method on `PageStack`, so pushing a page onto a pagestack isn't necessarily the same as simply pushing an item onto a stack, otherwise it would also not make sense for the `Push` method to remove duplicates before pushing.

Perhaps we can rename the `Push` method if the name gives the impression that it should do a simple stack append only.

**Comment by ukane-philemon** [comment]
IMO `Display` should have the responsibility of binding the new page with the navigator and executing the `OnNavigatedTo` method and it's more intuitive for `pageStack.Push` to just Push in a new page. This way we don't have to pass an argument to `Push` just to bind the new page which we can do in the caller if the push was successful.

Also, Given fixing #249, it's possible a caller wants to "Push" a page to the stack but doesn’t want to execute the `OnNavigatedTo` method.

**Comment by ukane-philemon** [comment]
> Perhaps we can rename the Push method if the name gives the impression that it should do a simple stack append only.

Sounds fine, maybe `PushAndNavigate`?

**Comment by ukane-philemon** [comment]
> > Perhaps we can rename the Push method if the name gives the impression that it should do a simple stack append only.
> 
> Sounds fine, maybe `PushAndNavigate`? i.e if we want to keep the current behaviour.

@dreacot what do you think?

**Comment by dreacot** [comment]
> > > Perhaps we can rename the Push method if the name gives the impression that it should do a simple stack append only.
> > 
> > 
> > Sounds fine, maybe `PushAndNavigate`? i.e if we want to keep the current behaviour.
> 
> @dreacot what do you think?

that works
