### ISSUE TITLE
asset slider shows half height on macos

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#261]
mixer needs to be enabled to notice this, as it happens when the asset slider shares the screen width with the mixer card

![Image](https://github.com/crypto-power/cryptopower/assets/25265396/bd0e6153-36ff-4e87-8bd2-ad568966e143)

**Comment by dreacot** [comment]
this is on fullscreen, the height is over extended

![Screenshot from 2023-11-28 13-23-58](https://github.com/crypto-power/cryptopower/assets/25265396/a95bda26-3910-4213-91ad-5ddb796d2ec7)

**Comment by JustinBeBoy** [comment]
> this is on fullscreen, the height is over extended
> 
> ![Screenshot from 2023-11-28 13-23-58](https://private-user-images.githubusercontent.com/25265396/286392094-a95bda26-3910-4213-91ad-5ddb796d2ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzQ2MzAsIm5iZiI6MTcwMTgzNDMzMCwicGF0aCI6Ii8yNTI2NTM5Ni8yODYzOTIwOTQtYTk1YmRhMjYtMzkxMC00MjEzLTkxYWQtNWRkYjc5NmQyZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAzNDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNWEyYzFkMzJmMDQ4Y2EzMzA4Y2ZjMTNmNWU4Yjk2OWQ5NzI3MTZiNTgxNmU5NzUzM2YwZjA5NDA5NGQ5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y2vbCWz_xiF8lHPhY0bCSu7fVFTZrAPTMB9jTzNkK3g)

I think we should just center the logo and text for the slider.
