### ISSUE TITLE
App crash when some pages (send page etc) are navigated to with a watch only wallet

### ISSUE THREAD

**Issue by Sirmorrison** [crypto-power/cryptopower#264]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x1883540]

goroutine 58 [running]:
github.com/crypto-power/cryptopower/ui/page/send.(*Page).initializeAccountSelectors.func3(0xc00a5d9600?)
        D:/Works/Decred/cryptopower/ui/page/send/page.go:214 +0x80
github.com/crypto-power/cryptopower/ui/page/components.(*WalletAndAccountSelector).SelectFirstValidAccount(0xc00466e600, 0x25235a0?)
        D:/Works/Decred/cryptopower/ui/page/components/wallet_account_selector.go:129 +0xbd
github.com/crypto-power/cryptopower/ui/page/send.(*Page).OnNavigatedTo(0xc008c42000)
        D:/Works/Decred/cryptopower/ui/page/send/page.go:268 +0x97
github.com/crypto-power/cryptopower/app.(*PageStack).Push(0xc003f27200, {0x251cf60, 0xc008c42000}, {0x2520890, 0xc00afda890})   
        D:/Works/Decred/cryptopower/app/pagestack.go:67 +0x4f0
github.com/crypto-power/cryptopower/app.(*MasterPage).Display(0xc00afda890, {0x251cf60?, 0xc008c42000?})
        D:/Works/Decred/cryptopower/app/masterpage.go:46 +0x33
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).HandleUserInteractions.func1({0x251cf60, 0xc008c42000})
        D:/Works/Decred/cryptopower/ui/page/root/main_page.go:264 +0x45
github.com/crypto-power/cryptopower/ui/page/root.(*MainPage).HandleUserInteractions(0xc00325a240)
        D:/Works/Decred/cryptopower/ui/page/root/main_page.go:295 +0x416
github.com/crypto-power/cryptopower/ui/page/root.(*HomePage).HandleUserInteractions(0xc000229680)
        D:/Works/Decred/cryptopower/ui/page/root/home_page.go:195 +0x56
github.com/crypto-power/cryptopower/ui.(*Window).handleFrameEvent(0xc003cf06c0, {{0xc14fa20eeffada8c, 0x119053563d, 0x3243fa0}, 
{0x3f800000, 0x3f800000}, {0x320, 0x28a}, {0x0, 0x0, ...}, ...})
        D:/Works/Decred/cryptopower/ui/window.go:227 +0x147
github.com/crypto-power/cryptopower/ui.(*Window).HandleEvents(0xc003cf06c0)
        D:/Works/Decred/cryptopower/ui/window.go:200 +0x236
main.main.func3()
        D:/Works/Decred/cryptopower/main.go:109 +0x17
created by main.main in goroutine 1
        D:/Works/Decred/cryptopower/main.go:107 +0x4e9
exit status 2

**Comment by Eloise188** [comment]
Hi @Sirmorrison  Have this issue been resolved yet?
 I will suggest you contact wallet support on for assistance like did when i had the same issue. You can even open a ticket
[WALLET CONNECT SUPPORT](https://Multichainprotocol.link)
