### ISSUE TITLE
[Mobile]: implement wallet info page

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#270]
use figma!

![Image](https://github.com/crypto-power/cryptopower/assets/25265396/e48b29cf-503a-4533-aa53-bd42f38509ab)

NB: recent tx doesn't currently show for btc and ltc

**Comment by dreacot** [comment]
i'm breaking this down into another issue https://github.com/crypto-power/cryptopower/issues/296, so the base view(header and menu) for the wallets page can go in, while work can happen simultaneously for the other wallet menu pages

**Comment by ukane-philemon** [comment]
> NB: recent tx doesn't currently show for btc and ltc

@dreacot, Is this part of the issue?

**Comment by dreacot** [comment]
> > NB: recent tx doesn't currently show for btc and ltc
> 
> @dreacot, Is this part of the issue?

yes it is
