### ISSUE TITLE
the general wallets page should have "all wallets" as part of the dropdown options

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#305]
![Screenshot from 2023-12-04 11-21-49](https://github.com/crypto-power/cryptopower/assets/25265396/b00ee397-c83f-46b1-b4e3-6c191b9ee1af)
![Screenshot from 2023-12-04 11-22-04](https://github.com/crypto-power/cryptopower/assets/25265396/b2a21515-c5a3-4efa-b2b0-9a11501a9539)

**Comment by ukane-philemon** [comment]
Does adding the All wallets option apply to staking activities?

**Comment by dreacot** [comment]
> Does adding the All wallets option apply to staking activities?

Yes
