### ISSUE TITLE
fix filtering and searching for the trade history page

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#341]
1. add "All Severs" and "All" as part of the server dropdown and status dropdown respectively

![Image](https://github.com/crypto-power/cryptopower/assets/25265396/5ce98c89-1a2c-40fd-8898-4bf1c2a25398)

2.  fix the filtering for the newest/oldest dropdown, and fix filtering for the server drodpdown

3. fix the search bar

**Comment by JustinBeBoy** [comment]
I have checked the code, the order and select server logic not implement so we need to implement that in this issue

**Comment by dreacot** [comment]
No problem
