### ISSUE TITLE
[Mobile] App freezes when turn on sync the wallet

### ISSUE THREAD

**Issue by JustinBeBoy** [crypto-power/cryptopower#357]
Some mobile devices freeze when turn on sync the wallet. Need to optimize the sync for mobile mode

**Comment by JoeGruffins** [comment]
Were you able to get a vid of this? Ill try if I can as well.

**Comment by JoeGruffins** [comment]
Wait, what wallet? If it's btc that one crashes for me most of the time on linux. I think it's on a bad commit as well.

**Comment by JoeGruffins** [comment]
Nevermind, the btcwallet commit is fine. I thought it was using an older one.
