### ISSUE TITLE
Allow to customize all settings on start page

### ISSUE THREAD

**Issue by JustinBeBoy** [crypto-power/cryptopower#451]
First time to open the application, allow user to customize all setting when they choose

**Comment by dreacot** [comment]
https://matrix.to/#/!oxOZZtibVUXxXtdPJS:decred.org/$TB_P_kASilD1-ZR6AArHUxVZMr-j8-p3U2VKMktc2wk?via=decred.org&via=matrix.org

> oh wow, I think I chose Advanced then and just forgot it was there. It's great it's already there! But, I think the meaning of this screen (and effects that follow) could be improved with what I've described above, namely

> (based on your screenshot from above) seems like the category of users who "want most user-friendly defaults, yet an ability to customize or check ALL the settings there are later on" is probably missing ?
so, I think it makes more sense to differentiate

> not between those who like to tweak settings, and those who dont (which what it currently seems to suggest)
but rather between those who prefer best UX, and those who want max privacy

**Comment by dreacot** [comment]
![image](https://github.com/crypto-power/cryptopower/assets/25265396/5a45ed47-ac6b-4fe1-814f-87659ff01e35)
