### ISSUE TITLE
combine the sync and balance sliders on the overview page into one slider

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#504]
![Screenshot from 2024-05-06 12-37-42](https://github.com/crypto-power/cryptopower/assets/25265396/0f547ec5-001b-4d83-9a03-6f9c39af46f9)

**Comment by ukane-philemon** [comment]
Do we have a design for this? @dreacot

**Comment by dreacot** [comment]
no it's currently backlogged

**Comment by ukane-philemon** [comment]
Oh, gotcha.

**Comment by dreacot** [comment]
duplicate of https://github.com/crypto-power/cryptopower/issues/463
