### ISSUE TITLE
Fix UI mishaps on restore wallet page

### ISSUE THREAD

**Issue by ukane-philemon** [crypto-power/cryptopower#506]
Some cosmetic changes. 

All the words are entirely almost invisible in dark mode:
<img width="779" alt="Screenshot 2024-05-04 at 9 57 02 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/abd9c407-7b78-4dfd-b6eb-ff2558d86f7f">

The top of the restore page needs some margin.
<img width="802" alt="Screenshot 2024-05-04 at 9 59 48 PM" src="https://github.com/crypto-power/cryptopower/assets/57448127/4fd0bed9-7129-4c95-8af4-ab9cee334ba6">

**Comment by JustinBeBoy** [comment]
it done with #507
