### ISSUE TITLE
the governance page doesn't auto refresh after fetching proposal updates

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#514]
![image](https://github.com/crypto-power/cryptopower/assets/25265396/bbf4f24e-44ac-45b6-bada-03eb6d7a1119)

**Comment by JustinBeBoy** [comment]
Data is duplicated when loading more

**Comment by JustinBeBoy** [comment]
proposal row wrong position when searching

![image](https://github.com/crypto-power/cryptopower/assets/19331824/a569d324-b4a5-42ad-ac7d-3a883d1c8806)

**Comment by JustinBeBoy** [comment]
Scroll not reset when change filter


![image](https://github.com/crypto-power/cryptopower/assets/19331824/c9cf101c-611c-4a23-89a8-1a0730f63f39)
