### ISSUE TITLE
restore: Current 12 word logic is not compatible with trust / exodus / trezor wallets.

### ISSUE THREAD

**Issue by JoeGruffins** [crypto-power/cryptopower#518]
The current restore from seed for 12 words does not match that in some mobile wallets. The ones I know of use the trezor library.

Currently we do:
https://github.com/crypto-power/cryptopower/blob/e507ac0ff880c0578040308fc560317420174dbe/libwallet/assets/wallet/wallet_utils.go#L249

But to be compatible with the mentioned wallets, it would need to be:
```
import (
	"crypto/sha512"

	"golang.org/x/crypto/pbkdf2"
)

hashedSeed := pbkdf2.Key([]byte(seedMnemonic), []byte("mnemonic"), 2048, 64, sha512.New)
```

It's important to note one difference here is that our current logic allows going from seed <-> mnemonic back and forth but the trezor way only allows for a one way mnemoinc -> seed

One idea to handle this is another seed type that uses the trezor logic.

Also leaving some test data that can be used: https://github.com/trustwallet/wallet-core/blob/484dc2a98c7a7ed9023ebae6fe30b1e331fff6e0/trezor-crypto/crypto/tests/test_check.c#L5146

**Comment by dreacot** [comment]
we can ask somewhere during the restore process if they are restoring from an external wallet

**Comment by JoeGruffins** [comment]
@dreacot It is done in a few places, try this branch https://github.com/JoeGruffins/cryptopower/tree/usetrezorseedlogic

I also hits some panics there, unsure if related to changes. I know you can paste the seed words there and it worked.

**Comment by JustinBeBoy** [comment]
> It's important to note one difference here is that our current logic allows going from seed <-> mnemonic back and forth but the trezor way only allows for a one way mnemoinc -> seed

I don't think so, when you restore wallet from seed on trust wallet it also converts the mnemonic to the seed for creating the wallet

**Comment by JoeGruffins** [comment]
yes?
