### ISSUE TITLE
when in full screen the governance page remains too small

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#52]
<img width="1250" alt="Screenshot 2023-08-24 at 5 20 28 PM" src="https://github.com/crypto-power/cryptopower/assets/25265396/a39b03c2-8fd3-49f3-9af3-8434263fe6c7">

**Comment by Vanvians** [comment]
Unable to replicate Issue
![Screenshot 2023-09-09 024305](https://github.com/crypto-power/cryptopower/assets/54014025/6c072472-492c-4886-88e6-fa18ad78ac4e)

**Comment by dreacot** [comment]
this should be resolved in #75
