### ISSUE TITLE
"Est. sync completion time" is very inaccurate.

### ISSUE THREAD

**Issue by dmigwi** [crypto-power/cryptopower#538]
The whole sync progress took close to an hour but the app gave a maximum estimate of 13 minutes.

<img width="772" alt="Screenshot 2024-06-18 at 14 24 44" src="https://github.com/crypto-power/cryptopower/assets/22055953/c0729020-90e9-4136-9ddc-381358fd1ef7">

**Comment by dmigwi** [comment]
The application now seems to be stuck.
There seems to be a background loop or routine that isn't exiting....

<img width="1223" alt="Screenshot 2024-06-18 at 15 34 04" src="https://github.com/crypto-power/cryptopower/assets/22055953/41ac2aba-175f-4a68-89a8-707ce55fb790">

**Comment by dmigwi** [comment]
Duplicate off: https://github.com/crypto-power/cryptopower/issues/472

**Comment by dreacot** [comment]
resolved by https://github.com/crypto-power/cryptopower/pull/563
