### ISSUE TITLE
Wallet created from backup words ought not to require a backup user action anymore

### ISSUE THREAD

**Issue by dmigwi** [crypto-power/cryptopower#542]
<img width="754" alt="Screenshot 2024-06-19 at 17 41 27" src="https://github.com/crypto-power/cryptopower/assets/22055953/d982477b-2ed7-475a-a0ef-85e83acfdcc0">

**Comment by dreacot** [comment]
this was resolved via this commit https://github.com/crypto-power/cryptopower/pull/558/commits/4dcf5cc019d2a14fb499115dcc59fbd05e053853
