### ISSUE TITLE
Sync button response time in UI.

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#546]
Toggling the sync button on/off has some lag before the button responds.

Also auto start sync after creating/restoring a new wallet

![Screenshot from 2024-06-21 10-52-16](https://github.com/crypto-power/cryptopower/assets/25265396/082a8ae6-a6a1-41b5-b5b9-f1a8d30b9bcd)

**Comment by frank269** [comment]
This issue has been resolved in a master branch

**Comment by bugjt** [comment]
In lastest code, this issue has been resolved in a master branch.

**Comment by dreacot** [comment]
> In lastest code, this issue has been resolved in a master branch.

no more lag in the sync button?

sync auto starts when creating a new wallet as well? backup, then delete your data dir and try again

**Comment by bugjt** [comment]
Sorry, I tested on the old code by mistake. I will check and fix it.

**Comment by dreacot** [comment]
resolved by https://github.com/crypto-power/cryptopower/pull/563
