### ISSUE TITLE
Inconsistent Total balance update on a new tx

### ISSUE THREAD

**Issue by dmigwi** [crypto-power/cryptopower#547]
![Screenshot 2024-06-22 at 13 55 13-editted](https://github.com/crypto-power/cryptopower/assets/22055953/f930afbd-f966-4d25-940c-da2a71324b27)

**Comment by JustinBeBoy** [comment]
@dmigwi 
Please provide more information to reproduce

**Comment by dmigwi** [comment]
This is a UI issue screen update issue, Implement a way that updates the balances within `OnNavigatedTo()` method.
