### ISSUE TITLE
some dropdown menus open as dialogs

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#552]
1. Currently some dropdowns open as a dialog e.g

-  the select asset dropdown while trying to create a wallet should take similar format as seen on the setup page when first launching the app, during the onboarding process

- other page content should not show until an asset type has been selected

![Screenshot from 2024-06-24 08-52-21](https://github.com/crypto-power/cryptopower/assets/25265396/2b49b81b-dc9b-42aa-843e-81b03da20ad7)

![Screenshot from 2024-06-24 08-54-02](https://github.com/crypto-power/cryptopower/assets/25265396/781ed6b9-7705-4cbb-b74e-9b557f70a136)

- the language dropdown should be moved to the top right of the setup page
- the back button arrow should be changed to the same style as used on the create wallet page, and should maintain the same consistency app wide

e.g 
Language -> [Dropdown]
Asset Type -> [Dropdown]

2. Drop down menu click away bug.

- While the language dropdown is open, clicking away doesn't close the dropdown, clicking away should close the dropdown

**Comment by bugjt** [comment]
The language selection moved to the top right will overlap with the back button text on mobile screens, so I will remove the title for mobile screens.

**Comment by JustinBeBoy** [comment]
> The language selection moved to the top right will overlap with the back button text on mobile screens, so I will remove the title for mobile screens.

okay, np
