### ISSUE TITLE
auto mixer setup duplicates mixed/unmixed accounts

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#555]
i had accounts already named "mixed" and "unmixed" in my wallet. but stakeshuffle seemed to think i no longer had mixing enabled because the account names start with a lower case.

I proceeded to setup auto setup mixer, which created accounts "Mixed" and "Unmixed". this was super confusing, i don't believe the capitalization of the first letter should be a problem, mixed/unmixed accounts should be detected irrespective of capitalization

![Screenshot from 2024-06-26 08-56-06](https://github.com/crypto-power/cryptopower/assets/25265396/aaf12e09-be51-4d29-bde2-aa3556344228)

**Comment by JustinBeBoy** [comment]
I have researched the logic of stakeshuffle when set mixed/unmixed account, it only use account number for save, so I think your case not related to name of mixed/unmixed account

I also tested it on my wallet after i change the name of mixed/unmixed account still get correct account

**Comment by JustinBeBoy** [comment]
May be we need disable setting mixed/unmixed account when mixer is running

![image](https://github.com/crypto-power/cryptopower/assets/19331824/2e4d8a8e-2251-44cf-9743-3588f44ab2b5)
