### ISSUE TITLE
on the send page, the info icon on the "from" modal is in a weird position

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#556]
on the send page, the info icon on the "from" modal is in a weird position, it should be right beside the "from" text.

clicking on the info icon expands the modal rather than opening another modal

![Screenshot from 2024-06-26 10-35-48](https://github.com/crypto-power/cryptopower/assets/25265396/9bdea4f0-2fc1-4c46-8298-c4d4a3588e90)

**Comment by JustinBeBoy** [comment]
this issue will close with #552
