### ISSUE TITLE
Dark Mode - Seed backup for LTC wallet not showing seed words

### ISSUE THREAD

**Issue by exitus1** [crypto-power/cryptopower#58]
A small problem I had in dark mode.

**Comment by Vanvians** [comment]
I am unable to replicate this issue please include screenshots.
Wallet type-LTC-
![Screenshot 2023-09-09 021337](https://github.com/crypto-power/cryptopower/assets/54014025/c32e1344-9b20-4624-9d53-52ea31f11c7d)

Seed words-
![Screenshot 2023-09-09 021212](https://github.com/crypto-power/cryptopower/assets/54014025/a41cb10d-eeb6-48dc-8212-0093ca089e22)

**Comment by exitus1** [comment]
Ok I just retried and they showed up in dark mode, not sure what happened yesterday.
