### ISSUE TITLE
Cache Consensus Changes data after its fetched

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#591]
- [x]  Cache Consensus Changes data after its fetched
- [x] Fix updated indicator disappears after 1s in "Consensus Changes" page
- [x] Syncing on Proposals and Consensus Changes views needs to run periodically (X min) and have a clickable option to refresh
- [x] Clicking on a proposal from the overview page embeds the proposal view into the overview page. Expected behaviour is to go to the Governance proposal view.

**Comment by bugjt** [comment]
I'm working on this

**Comment by JustinBeBoy** [comment]
@bugjt why this issue has resolved but not close?
