### ISSUE TITLE
send page bugs

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#592]
- [ ] trying to do a test send from one wallet to another using 'Wallets' option on send page. Destination account provides nothing to select, so its no possible to complete the send. Appears to be an issue if the destination account has a 0 balance.
- [x] Click on the QR code Or the address to copy this text, Position of the toast is not shown in the right place
- [x] "Amount (DCR)" input show place holder when input selected
- [x] Remove hover on "MAX" button, change text to "Max"
- [ ] Keep the password confirmation modal in send page always visible even if an incorrect password is entered
- [x] 'You're about to send' page, 'To' label and address are out of bottom vertical alignment. Grey line in the middle is oddly placed and has inconsistent white space above and below.
- [x]  Clicking on send appears to show a partial circle that I believe is suppose to be an progress animation, but there is no animation.
- [ ] Cannot click the send button if the wallet does not have a password
- [x] Cannot focus on password input
- [x] Clear error when updating password input
- [x] Clicking in the field and holding down the mouse button for some reason causes the 'Spending passphrase' title to disappear.
- [x] Expected behaviour for me after transaction send is to go to the view of the transaction, rather then returning to empty send page. At minimum, have a button to click from the 'Sent!' dialog that will take the user there.
- [x] Show loading indicator instead of "No transaction" text when selecting between 'Regular Transactions' and 'Staking Transactions'
- [x] Add X or Cancel button to Send/Receive Modal to close modal

**Comment by JustinBeBoy** [comment]
@dreacot 

> trying to do a test send from one wallet to another using 'Wallets' option on send page. Destination account provides nothing to select, so its no possible to complete the send. Appears to be an issue if the destination account has a 0 balance.

it work for me
<img width="720" alt="image" src="https://github.com/user-attachments/assets/aaf4741c-7320-4c32-9bf7-5ee6ba2fce07">


>  Click on the QR code Or the address to copy this text, Position of the toast is not shown in the right place

you mean add click to QR or the address to copy address?
current position of the toast show like below, is it right?

<img width="788" alt="image" src="https://github.com/user-attachments/assets/b918da1b-5634-44b9-b841-2c4643608aba">

> Keep the password confirmation modal in send page always visible even if an incorrect password is entered

it still there when password incorrect

>  Cannot click the send button if the wallet does not have a password

Can we create the wallet without password?
