### ISSUE TITLE
Full screen desktop hides the 'copy' button in recieve tab (image)

### ISSUE THREAD

**Issue by exitus1** [crypto-power/cryptopower#60]
![image](https://github.com/crypto-power/cryptopower/assets/46197055/845f1ab8-f45c-400f-a505-2709129841a3) - full screen
![image](https://github.com/crypto-power/cryptopower/assets/46197055/d18880c2-1e6f-48f7-be95-d6f238932ba1) - smaller window

**Comment by dreacot** [comment]
@jcezetah

**Comment by Vanvians** [comment]
I am unable to replicate this issue.

![Screenshot 2023-09-09 013453](https://github.com/crypto-power/cryptopower/assets/54014025/f70f8c32-5891-47c9-ab65-7c766efde821)
-Smaller Screen

![Screenshot 2023-09-09 013522](https://github.com/crypto-power/cryptopower/assets/54014025/8c7097a7-82d0-4a98-832e-bd24221552c1)
-Full Screen

**Comment by exitus1** [comment]
Can anyone else test this? Still having the same issue on my laptop's 2560 x 1440 screen

**Comment by dreacot** [comment]
this should be resolved in #75
