### ISSUE TITLE
Cannot scroll on restore wallet page on Android

### ISSUE THREAD

**Issue by bugjt** [crypto-power/cryptopower#623]
Cannot scroll on restore wallet page on Android

![Screenshot_1723209399](https://github.com/user-attachments/assets/6d3b4a60-6214-4b7d-85d4-86f9c444691f)

**Comment by xcelente** [comment]
I am painfully trying to use this wallet and can confirm the seed phrase entry just to sign up / recover is AWFUL.

Sorry, not intending to offend, but I just can't imagine the reaction of new users having to go through this process:

Yes, can confirm there are big issues regarding input of words. Keyboard can sometimes hide what is being entered, or the list has jumped up or down. Might be entering word into wrong slot or enter a word twice by mistake. All this has happened to me.

Current word prediction needs to be larger and with color,. This is the current position I am working on and no need to have empty slots below. Tbh, I think this part needs a re-write.

Also, I am sure you've been told this before; 33 words is too much. I understand the potential disadvantages of a 12 word seed and 18 or 24 words are standard in this space. I've onboarded many people with other wallets and I can tell you, noobs are going to hate 33 words.

From a technical perspective, I get that copy-paste / screenshots etc are bad, but as a mobile wallet - a hot wallet intended to hold small day-to-day spending - this is one more reason why they will not recommend to others without big incentives.

Finally, I restore a wallet and now find out that it's going to sync the whole bloody chain! My time and phone space making this even more painful. No no no, this user experience is not like dash or even electrum.

**Comment by JustinBeBoy** [comment]
> I am painfully trying to use this wallet and can confirm the seed phrase entry just to sign up / recover is AWFUL.
> 
> Sorry, not intending to offend, but I just can't imagine the reaction of new users having to go through this process:
> 
> Yes, can confirm there are big issues regarding input of words. Keyboard can sometimes hide what is being entered, or the list has jumped up or down. Might be entering word into wrong slot or enter a word sequentially twice by mistake. All this has happened to me.
> 
> Current word prediction needs to be larger and with color,. This is the current position I am working on and no need to have empty slots below. Tbh, I think this part needs a re-write.
> 
> Also, I am sure you've been told this before; 33 words is too much. I understand the potential disadvantages of a 12 word seed and 18 or 24 words are standard in this space. I've onboarded many people with other wallets and I can tell you, noobs are going to hate 33 words.
> 
> From a technical perspective, I get that copy-paste / screenshots etc are bad, but as a mobile wallet - a hot wallet intended to hold small day-to-day spending - this is one more reason why they will not recommend to others without big incentives.
> 
> Finally, I restore a wallet and now find out that it's going to sync the whole bloody chain! My time and phone space making this even more painful. No no no, this user experience is not like dash or even electrum.

thank you for your feedback, 

> I am painfully trying to use this wallet and can confirm the seed phrase entry just to sign up / recover is AWFUL.
> 
> Sorry, not intending to offend, but I just can't imagine the reaction of new users having to go through this process:
> 
> Yes, can confirm there are big issues regarding input of words. Keyboard can sometimes hide what is being entered, or the list has jumped up or down. Might be entering word into wrong slot or enter a word sequentially twice by mistake. All this has happened to me.
> 
> Current word prediction needs to be larger and with color,. This is the current position I am working on and no need to have empty slots below. Tbh, I think this part needs a re-write.
> 
> Also, I am sure you've been told this before; 33 words is too much. I understand the potential disadvantages of a 12 word seed and 18 or 24 words are standard in this space. I've onboarded many people with other wallets and I can tell you, noobs are going to hate 33 words.
> 
> From a technical perspective, I get that copy-paste / screenshots etc are bad, but as a mobile wallet - a hot wallet intended to hold small day-to-day spending - this is one more reason why they will not recommend to others without big incentives.
> 
> Finally, I restore a wallet and now find out that it's going to sync the whole bloody chain! My time and phone space making this even more painful. No no no, this user experience is not like dash or even electrum.

- In fact, cryptopower is working on many issues for mobile applications
- Cryptopower has also supported the use of hex seeds and pasting seeds when restoring
- Cryptopower is an SPV wallet so it will need to be synchronized to process transactions
- All popular wallets are lite wallets so it is understandable that there is no need to synchronize
- Currently Cryptopower has supported 12, 24 seed words so you can use seeds from other wallets on Cryptopower

It is great to receive your comments

**Comment by bugjt** [comment]
Resolved on #635
