### ISSUE TITLE
implement the overview page design

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#69]
![CRYPTOPOWER](https://github.com/crypto-power/cryptopower/assets/25265396/d8ae93bf-6574-4cd2-b65b-ebc02e96612c)

**Comment by xaur** [comment]
Screenshots of the actual implementation in #75 and #115 look a bit different, e.g.

- Column labels "ID Change" ("1D CHANGE" in the design), "Price" (not "PRICE")
- numbers are not formatted (no thousand separator, no decimal places)
- Fonts used for numbers look pale/lower contrast vs the design
- No subtle shadow box around the tiles
- Section titles are smaller than in the design

I guess this will be polished in future PRs? Is there an issue for testing the final implementation against the design specs?

**Comment by dreacot** [comment]
good catch @xaur , some comments have been resolved, but yes, others would be cleaned up in follow up PRs

> Is there an issue for testing the final implementation against the design specs?

not at the moment
