### ISSUE TITLE
trying to exit wallet back up process doesn't work

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#72]
clicking on the yes button does nothing

https://github.com/crypto-power/cryptopower/assets/57448127/3da43f49-fe4a-49ac-815b-5ec42bc55afe

<img width="797" alt="Screenshot 2023-09-20 at 6 08 23 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/ac140085-06c9-4d28-a328-f07dba45d96a">

**Comment by Vanvians** [comment]
Unable to replicate. I am able to exit the back up process from any stage.

**Comment by dreacot** [comment]
this should be resolved in #75

**Comment by JoeGruffins** [comment]
I also cannot seem to reproduce.

**Comment by dreacot** [comment]
@ukane-philemon you were able to replicate this right? can you work on this?

**Comment by JoeGruffins** [comment]
I was able to reproduce just now on master with a new cryptopower:

https://github.com/crypto-power/cryptopower/assets/34998433/f0e33039-a2ef-48e0-8021-592d1445a828

**Comment by itswisdomagain** [comment]
I've had this issue for sometime.

**Comment by JoeGruffins** [comment]
After I backup the wallet stuck on this screen

![image](https://github.com/crypto-power/cryptopower/assets/34998433/8700e87a-5646-4676-9670-15af811333fa)

**Comment by ukane-philemon** [comment]
@JoeGruffins do you mean nothing happened when you click the “Back to Wallets” button? The page does not auto redirect.
