### ISSUE TITLE
implement api to show market overview on the overview page

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#78]
1. by the top right of the card, there is an option to refresh the data, and see the last refresh rate. refreshing this data manually should also update the USD values for all assets. If the USD value for all assets is being updated for whatever reason, the market overview should also be update, since they are all market related data

2. if the fetch exchange rate api is enabled, then this card becomes visible, if the api is disabled, then this card becomes hidden

the market order should be;
Decred
Bitcoin
Litecoin

![Screenshot from 2023-10-03 09-27-50](https://github.com/crypto-power/cryptopower/assets/25265396/117fd2d4-9204-4c93-95fe-4dc076f546f7)

**Comment by ukane-philemon** [comment]
I'd be looking at implementing WebSockets instead of making API requests each time.
