### ISSUE TITLE
implement the new design for the landing page of the trade tab

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#80]
<img width="601" alt="Screenshot 2023-09-24 at 4 31 06 PM" src="https://github.com/crypto-power/cryptopower/assets/25265396/e5bef140-51af-4d2e-8451-80ae60153bf9">

**Comment by ukane-philemon** [comment]
@Vanvians still on this?

**Comment by dreacot** [comment]
There's a new layout as seen in the screenshot, we should make use of segmented control

https://github.com/crypto-power/cryptopower/pull/139#issuecomment-1757306273
