### ISSUE TITLE
[overview page]: populate the recent trades card with real data

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#85]
use figma!

i'm not certain if this card should show data from both centralised exchanges and dcrdex, or if we should have 2 separate cards for the data @itswisdomagain thoughts?

<img width="767" alt="Screenshot 2023-09-25 at 2 34 16 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/4af442b3-de32-45b6-aeeb-eb14df9566b1">

**Comment by itswisdomagain** [comment]
The screenshot above looks incomplete but I think I've seen the UI on figma. I think that section can show all trade/swap information from all exchanges, sorted by time perhaps. No need to have different sections for dcrdex and a separate one for centralized exchanges.

Each card should probably also show where the trade/swap happened, the name of the CEX, if it's a CEX or the DEX server name if it was a DEX trade.

**Comment by dreacot** [comment]
correct although this would need an updated design, so might cause delays for you

although you can work on populating the recent trade meanwhile, pending when the design for this is done
