### ISSUE TITLE
show the corresponding page when the general app send page is clicked

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#89]
<img width="778" alt="Screenshot 2023-09-25 at 2 44 55 AM" src="https://github.com/crypto-power/cryptopower/assets/25265396/080851c8-52bf-4595-8bee-ce4ab73b18d3">

to reduce development time, same send page can be used in the modal, just need to allow picking any wallet(btc,dcr,ltc)

![Screenshot from 2023-10-03 10-27-34](https://github.com/crypto-power/cryptopower/assets/25265396/6af3ce44-d840-4899-ad57-3772a7060951)

**Comment by Sirmorrison** [comment]
The only issue i have with this issue is how would you determine the selected wallet? should it default to decred, BTC or LTC?

**Comment by dreacot** [comment]
Take a look at the general receive page, the source wallet usually Defaults to a random dcr wallet, the existing wallet selector already automatically handles that logic
