### ISSUE TITLE
[overview page]: the asset balance card doesn't fill specified width

### ISSUE THREAD

**Issue by dreacot** [crypto-power/cryptopower#94]
on my linux this is what the overview page looks like, the asset balance card does not fill the required space

![Image](https://github.com/crypto-power/cryptopower/assets/25265396/d0fe51e3-a3d5-4e63-90af-07d6d307688b)

**Comment by JoeGruffins** [comment]
Can I tackle this. The DCR etc cards should be wider correct? They look the same for me so can confirm the behavior.
