### ISSUE TITLE
Update Code License

### ISSUE THREAD

**Issue by ukane-philemon** [crypto-power/cryptopower#97]
I've noticed that some parts of the code still made reference to Raedah Group when giving credits. I think we should:

1. Update the License file to mention Cryptopower developers (The Cyptopower Developers?)
2. All files should have any applicable License mentioned at the top
3. Copyright dates should be updated.

**Comment by dreacot** [comment]
I'm not sure if we can take out the original license, seeing as the license allowed use of the source code as long as that license remains, i had this conversation with @itswisdomagain previously but we never reached a conclusion

**Comment by ukane-philemon** [comment]
> I'm not sure if we can take out the original license

Yeah, I'm not suggesting to take it out in its entirety. We could just update the Copyright years and add our identity(Cryptopower Developers)?

**Comment by dreacot** [comment]
alright then, sounds fine
